FROM jenkins/jenkins:lts

USER root

# Cài đặt Docker CLI và Docker Compose CLI bên trong Jenkins container
RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli docker-compose-plugin nodejs npm && \
    rm -rf /var/lib/apt/lists/*

# Cấp quyền docker cho user jenkins
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins
